#!/usr/bin/env bash

RED="\033[31m"
GREEN="\033[32m"
TEXT="\033[0;39m"
bold=$(tput bold)
normal=$(tput sgr0)

echo ""

for dir in *
do
	if [ -d $dir/.git ]
	then
		cd $dir
		echo -e "${bold}${dir}:${normal}"
		git pull --rebase
		echo ""
		cd ..
	else
		echo -e "${bold}${dir}:${normal}"
		echo -e "${RED}Not a git repository.${normal}\n"
		sleep 0.3
	fi
done

echo -e "\n${GREEN}All repositories synced.${TEXT}\n"
